### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by nikgustafson** [applitools/eyes-testcafe#1]
I was wondering if there were any plans to include typescript types? And if they already exist how would one go about setting them up? 

I just started using this package to create a quick demo and I'm not able to find any types, but having them would make working with the package much easier. Thanks!

**Comment by danielschwartz85** [comment]
@nikgustafson sorry for the late response, yes we have plans including typescritp types.
will update here once it's done.

**Comment by danielschwartz85** [comment]
Added Typescript definition file
https://github.com/applitools/eyes-testcafe/blob/master/ts/index.d.ts in version 1.4.1
