### ISSUE TITLE
Missing assets/images in Applitools Dashboard results

### ISSUE THREAD

**Issue by mlukjanska** [applitools/eyes-testcafe#10]
In essence this is the same issue as described here for Percy: https://github.com/DevExpress/testcafe/issues/4169.

Due to the nature of Testcafe it prepends certain page assets with the test server IP in the DOM and when those assets need to be rendered in Applitools dashboard test result images the assets are in turn unreachable.  

Eg:
```html
<div id="shoe_img" class="product_details_img" style="background-image: url(&quot;grid/img/products/shoes/1.jpg&quot;);">
</div>
```

in Testcafe run is 
```html
<div id="shoe_img" class="product_details_img" style="background-image: url(&quot;http://192.168.1.146:49292/97KKFNhck*vUpzIpX1r/http://demo.applitools.com/grid/img/products/shoes/1.jpg&quot;);">
</div>
```

Is there any solution/workaround for this? 

Thanks!

**Comment by tourdedave** [comment]
@mlukjanska My hunch is that it's related to proxy changes in version 1.9.x of TestCafe. Can you confirm the same behavior when running with the TestCafe version of 1.8.8? If you still have problems, please email support@applitools.com
